# Generated by Django 5.0.14 on 2026-07-07 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(default='DeFi Yield Agent', max_length=150)),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('total_cspr_spent', models.FloatField(default=0.0)),
                ('trust_score', models.FloatField(default=95.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('agent_id', models.CharField(max_length=100)),
                ('target_contract', models.CharField(max_length=150)),
                ('decision', models.CharField(max_length=20)),
                ('signed_jwt', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('agent_id', models.CharField(default='anonymous_agent', max_length=100)),
                ('amount_cspr', models.FloatField(default=2.5)),
                ('treasury_address', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid Verified'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('proof_tx_hash', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('agent_id', models.CharField(max_length=100)),
                ('ticker', models.CharField(default='CSPR/USD', max_length=50)),
                ('target_contract', models.CharField(max_length=150)),
                ('target_rpc', models.CharField(max_length=200)),
                ('decision', models.CharField(choices=[('GO', 'GO - Safe to Execute'), ('NO-GO', 'NO-GO - Blocked Risk')], max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('market_status', models.CharField(default='SAFE', max_length=100)),
                ('security_status', models.CharField(default='PASSED', max_length=100)),
                ('proof_hash', models.CharField(db_index=True, max_length=100)),
                ('casper_tx_hash', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
